import { NextResponse } from "next/server";
import { db, type Database } from "@/lib/postgres";


const id=()=>crypto.randomUUID();
const code=()=>Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("");
const json=(data:unknown,status=200)=>NextResponse.json(data,{status});

async function init(){await db.batch([
<<<<<<< HEAD
 db.prepare("CREATE TABLE IF NOT EXISTS rooms (code TEXT PRIMARY KEY, host_player_id TEXT, status TEXT NOT NULL DEFAULT 'active', turn INTEGER NOT NULL DEFAULT 1, created_at BIGINT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS players (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, name TEXT NOT NULL, token TEXT NOT NULL, balance INTEGER NOT NULL DEFAULT 1500, is_host INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', created_at BIGINT NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, from_player_id TEXT, to_player_id TEXT, amount INTEGER NOT NULL, type TEXT NOT NULL, note TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'completed', created_at BIGINT NOT NULL)"),
=======
 db.prepare("CREATE TABLE IF NOT EXISTS rooms (code TEXT PRIMARY KEY, host_player_id TEXT, status TEXT NOT NULL DEFAULT 'active', turn INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS players (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, name TEXT NOT NULL, token TEXT NOT NULL, balance INTEGER NOT NULL DEFAULT 1500, is_host INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', created_at INTEGER NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, from_player_id TEXT, to_player_id TEXT, amount INTEGER NOT NULL, type TEXT NOT NULL, note TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'completed', created_at INTEGER NOT NULL)"),
>>>>>>> 53d8969820331526ee8ea3a2c5a890626333253c
 db.prepare("CREATE TABLE IF NOT EXISTS properties (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, name TEXT NOT NULL, price INTEGER NOT NULL, rent INTEGER NOT NULL, owner_player_id TEXT, houses INTEGER NOT NULL DEFAULT 0, group_name TEXT NOT NULL DEFAULT 'Mandiri', house_price INTEGER NOT NULL DEFAULT 50, hotel_price INTEGER NOT NULL DEFAULT 50, sell_price INTEGER NOT NULL DEFAULT 0, rent_1 INTEGER NOT NULL DEFAULT 0, rent_2 INTEGER NOT NULL DEFAULT 0, rent_3 INTEGER NOT NULL DEFAULT 0, rent_4 INTEGER NOT NULL DEFAULT 0, rent_hotel INTEGER NOT NULL DEFAULT 0)"),
 db.prepare("CREATE TABLE IF NOT EXISTS room_settings (room_code TEXT PRIMARY KEY, starting_balance INTEGER NOT NULL DEFAULT 1500, go_salary INTEGER NOT NULL DEFAULT 200, max_players INTEGER NOT NULL DEFAULT 8, currency_symbol TEXT NOT NULL DEFAULT 'M', require_bank_approval INTEGER NOT NULL DEFAULT 1)"),
 db.prepare("CREATE TABLE IF NOT EXISTS board_spaces (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, position INTEGER NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, property_id TEXT, color TEXT NOT NULL DEFAULT '#e7dfcf')"),
 db.prepare("CREATE TABLE IF NOT EXISTS cards (id TEXT PRIMARY KEY, room_code TEXT NOT NULL, deck TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, amount INTEGER NOT NULL DEFAULT 0, enabled INTEGER NOT NULL DEFAULT 1)"),
<<<<<<< HEAD
 db.prepare("DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'rooms' AND column_name = 'created_at' AND data_type = 'integer') THEN ALTER TABLE rooms ALTER COLUMN created_at TYPE BIGINT USING created_at::BIGINT; END IF; IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'players' AND column_name = 'created_at' AND data_type = 'integer') THEN ALTER TABLE players ALTER COLUMN created_at TYPE BIGINT USING created_at::BIGINT; END IF; IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'transactions' AND column_name = 'created_at' AND data_type = 'integer') THEN ALTER TABLE transactions ALTER COLUMN created_at TYPE BIGINT USING created_at::BIGINT; END IF; END $$"),
=======
>>>>>>> 53d8969820331526ee8ea3a2c5a890626333253c
 db.prepare("CREATE INDEX IF NOT EXISTS idx_players_room ON players(room_code)"),db.prepare("CREATE INDEX IF NOT EXISTS idx_tx_room ON transactions(room_code, created_at DESC)")]);
 await db.batch([
  db.prepare("UPDATE properties SET group_name='Cokelat',house_price=50,hotel_price=50,sell_price=price/2,rent_1=CASE name WHEN 'Gang Kelinci' THEN 40 ELSE 60 END,rent_2=CASE name WHEN 'Gang Kelinci' THEN 100 ELSE 180 END,rent_3=CASE name WHEN 'Gang Kelinci' THEN 300 ELSE 500 END,rent_4=CASE name WHEN 'Gang Kelinci' THEN 450 ELSE 700 END,rent_hotel=CASE name WHEN 'Gang Kelinci' THEN 600 ELSE 900 END WHERE name IN ('Gang Kelinci','Jalan Merdeka') AND group_name='Mandiri'"),
  db.prepare("UPDATE properties SET group_name='Biru Muda',house_price=100,hotel_price=100,sell_price=price/2,rent_1=CASE name WHEN 'Jalan Anggrek' THEN 90 ELSE 150 END,rent_2=CASE name WHEN 'Jalan Anggrek' THEN 250 ELSE 450 END,rent_3=CASE name WHEN 'Jalan Anggrek' THEN 700 ELSE 1000 END,rent_4=CASE name WHEN 'Jalan Anggrek' THEN 875 ELSE 1200 END,rent_hotel=CASE name WHEN 'Jalan Anggrek' THEN 1050 ELSE 1400 END WHERE name IN ('Jalan Anggrek','Jalan Sudirman') AND group_name='Mandiri'"),
  db.prepare("UPDATE properties SET group_name='Hijau',house_price=200,hotel_price=200,sell_price=price/2,rent_1=CASE name WHEN 'Jalan Asia Afrika' THEN 200 ELSE 250 END,rent_2=CASE name WHEN 'Jalan Asia Afrika' THEN 600 ELSE 750 END,rent_3=CASE name WHEN 'Jalan Asia Afrika' THEN 1400 ELSE 1500 END,rent_4=CASE name WHEN 'Jalan Asia Afrika' THEN 1700 ELSE 1850 END,rent_hotel=CASE name WHEN 'Jalan Asia Afrika' THEN 2000 ELSE 2200 END WHERE name IN ('Jalan Asia Afrika','Taman Menteng') AND group_name='Mandiri'"),
  db.prepare("UPDATE properties SET group_name=CASE name WHEN 'Stasiun Utara' THEN 'Transportasi' ELSE 'Utilitas' END,house_price=0,hotel_price=0,sell_price=price/2 WHERE name IN ('Stasiun Utara','Perusahaan Air') AND group_name='Mandiri'")
 ]);return db}
async function valid(db:Database,roomCode:string,playerId:string){return db.prepare("SELECT * FROM players WHERE id=? AND room_code=? AND status='active'").bind(playerId,roomCode).first<any>()}
const n=(value:unknown,fallback=0)=>Math.max(0,Math.trunc(Number(value)||fallback));
async function groupProperties(db:Database,room:string,p:any){return (await db.prepare("SELECT * FROM properties WHERE room_code=? AND group_name=? ORDER BY price,id").bind(room,p.group_name).all<any>()).results}
async function ownsCompleteGroup(db:Database,room:string,p:any,owner:string){const group=await groupProperties(db,room,p);return group.length>1&&p.house_price>0&&group.every((x:any)=>x.owner_player_id===owner)}
async function effectiveRent(db:Database,room:string,p:any){if(p.houses===5)return p.rent_hotel;if(p.houses>0)return p[`rent_${p.houses}`]||p.rent;return (await ownsCompleteGroup(db,room,p,p.owner_player_id))?p.rent*2:p.rent}
const propertySeed=[
 ["Gang Kelinci",60,8,"Cokelat",50,[40,100,300,450,600]],
 ["Jalan Merdeka",100,12,"Cokelat",50,[60,180,500,700,900]],
 ["Jalan Anggrek",140,18,"Biru Muda",100,[90,250,700,875,1050]],
 ["Stasiun Utara",200,25,"Transportasi",0,[0,0,0,0,0]],
 ["Jalan Sudirman",240,30,"Biru Muda",100,[150,450,1000,1200,1400]],
 ["Perusahaan Air",150,20,"Utilitas",0,[0,0,0,0,0]],
 ["Jalan Asia Afrika",300,40,"Hijau",200,[200,600,1400,1700,2000]],
 ["Taman Menteng",350,50,"Hijau",200,[250,750,1500,1850,2200]]
];
const spaceSeed=[[0,"GO","go"],[1,"Gang Kelinci","property"],[2,"Dana Umum","fund"],[3,"Jalan Merdeka","property"],[4,"Pajak Penghasilan","tax"],[5,"Stasiun Utara","property"],[6,"Jalan Anggrek","property"],[7,"Kesempatan","chance"],[8,"Penjara / Berkunjung","jail"],[9,"Perusahaan Air","property"],[10,"Parkir Bebas","parking"],[11,"Jalan Sudirman","property"],[12,"Kesempatan","chance"],[13,"Jalan Asia Afrika","property"],[14,"Masuk Penjara","goto_jail"],[15,"Taman Menteng","property"]];
const cardSeed=[["chance","Hadiah lomba","Menang lomba lingkungan, terima M100",100],["chance","Perbaikan kendaraan","Bayar biaya perbaikan M50",-50],["chance","Maju ke GO","Terima gaji GO",200],["chance","Denda parkir","Bayar denda M25",-25],["fund","Warisan keluarga","Terima warisan M100",100],["fund","Biaya sekolah","Bayar biaya sekolah M50",-50],["fund","Pengembalian pajak","Terima pengembalian pajak M75",75],["fund","Biaya rumah sakit","Bayar biaya rumah sakit M100",-100]];

export async function POST(req:Request){try{const b=await req.json() as any;const db=await init();
 if(b.action==="create"){let c=code();while(await db.prepare("SELECT code FROM rooms WHERE code=?").bind(c).first())c=code();const pid=id(),now=Date.now();const props=propertySeed.map((p:any)=>({id:id(),name:p[0],price:p[1],rent:p[2],group:p[3],build:p[4],rents:p[5]}));await db.batch([db.prepare("INSERT INTO rooms(code,host_player_id,created_at) VALUES(?,?,?)").bind(c,pid,now),db.prepare("INSERT INTO players(id,room_code,name,token,is_host,created_at) VALUES(?,?,?,?,1,?)").bind(pid,c,String(b.name).slice(0,18),b.token,now),db.prepare("INSERT INTO room_settings(room_code) VALUES(?)").bind(c),...props.map(p=>db.prepare("INSERT INTO properties(id,room_code,name,price,rent,group_name,house_price,hotel_price,sell_price,rent_1,rent_2,rent_3,rent_4,rent_hotel) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(p.id,c,p.name,p.price,p.rent,p.group,p.build,p.build,Math.floor(p.price/2),...p.rents)),...spaceSeed.map(s=>{const prop=props.find(p=>p.name===s[1]);return db.prepare("INSERT INTO board_spaces(id,room_code,position,name,type,property_id) VALUES(?,?,?,?,?,?)").bind(id(),c,s[0],s[1],s[2],prop?.id||null)}),...cardSeed.map(x=>db.prepare("INSERT INTO cards(id,room_code,deck,title,description,amount) VALUES(?,?,?,?,?,?)").bind(id(),c,...x))]);return json({session:{roomCode:c,playerId:pid}})}
 if(b.action==="join"){const c=String(b.code||"").toUpperCase();if(!await db.prepare("SELECT code FROM rooms WHERE code=? AND status='active'").bind(c).first())return json({error:"Kode ruang tidak ditemukan"},404);const count=await db.prepare("SELECT COUNT(*) n FROM players WHERE room_code=? AND status='active'").bind(c).first<any>();const settings=await db.prepare("SELECT * FROM room_settings WHERE room_code=?").bind(c).first<any>();if(count.n>=(settings?.max_players||8))return json({error:`Ruang sudah penuh (maksimal ${settings?.max_players||8} pemain)`},409);const pid=id();await db.prepare("INSERT INTO players(id,room_code,name,token,balance,created_at) VALUES(?,?,?,?,?,?)").bind(pid,c,String(b.name).slice(0,18),b.token,settings?.starting_balance||1500,Date.now()).run();return json({session:{roomCode:c,playerId:pid}})}
 const room=String(b.roomCode||"");const me=await valid(db,room,String(b.playerId||""));if(!me)return json({error:"Sesi permainan tidak valid"},401);
 if(b.action==="state"){const [r,p,t,pr,s,sp,ca]=await Promise.all([db.prepare("SELECT code,status,turn FROM rooms WHERE code=?").bind(room).first(),db.prepare("SELECT id,name,token,balance,is_host,status FROM players WHERE room_code=? AND status='active' ORDER BY is_host DESC,created_at").bind(room).all(),db.prepare("SELECT * FROM transactions WHERE room_code=? ORDER BY created_at DESC LIMIT 60").bind(room).all(),db.prepare("SELECT * FROM properties WHERE room_code=? ORDER BY price").bind(room).all(),db.prepare("SELECT * FROM room_settings WHERE room_code=?").bind(room).first(),db.prepare("SELECT * FROM board_spaces WHERE room_code=? ORDER BY position").bind(room).all(),db.prepare("SELECT * FROM cards WHERE room_code=? ORDER BY deck,title").bind(room).all()]);return json({room:r,players:p.results,transactions:t.results,properties:pr.results,settings:s||{starting_balance:1500,go_salary:200,max_players:8,currency_symbol:"M",require_bank_approval:1},spaces:sp.results,cards:ca.results})}
 if(["save_settings","save_property","delete_property","save_space","save_card","delete_card"].includes(b.action)){
  if(!me.is_host)return json({error:"Hanya bankir yang dapat membuka panel admin"},403);
  if(b.action==="save_settings"){const x=b.settings||{};await db.prepare("INSERT INTO room_settings(room_code,starting_balance,go_salary,max_players,currency_symbol,require_bank_approval) VALUES(?,?,?,?,?,?) ON CONFLICT(room_code) DO UPDATE SET starting_balance=excluded.starting_balance,go_salary=excluded.go_salary,max_players=excluded.max_players,currency_symbol=excluded.currency_symbol,require_bank_approval=excluded.require_bank_approval").bind(room,Math.max(100,Number(x.starting_balance)||1500),Math.max(0,Number(x.go_salary)||0),Math.min(12,Math.max(2,Number(x.max_players)||8)),String(x.currency_symbol||"M").slice(0,3),x.require_bank_approval?1:0).run()}
  if(b.action==="save_property"){const x=b.property||{},pid=String(x.id||id());if(!String(x.name||"").trim())return json({error:"Nama properti wajib diisi"},400);await db.prepare("INSERT INTO properties(id,room_code,name,price,rent,owner_player_id,houses,group_name,house_price,hotel_price,sell_price,rent_1,rent_2,rent_3,rent_4,rent_hotel) VALUES(?,?,?,?,?,NULL,0,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,price=excluded.price,rent=excluded.rent,group_name=excluded.group_name,house_price=excluded.house_price,hotel_price=excluded.hotel_price,sell_price=excluded.sell_price,rent_1=excluded.rent_1,rent_2=excluded.rent_2,rent_3=excluded.rent_3,rent_4=excluded.rent_4,rent_hotel=excluded.rent_hotel").bind(pid,room,String(x.name).slice(0,40),n(x.price),n(x.rent),String(x.group_name||"Mandiri").slice(0,30),n(x.house_price),n(x.hotel_price),n(x.sell_price),n(x.rent_1),n(x.rent_2),n(x.rent_3),n(x.rent_4),n(x.rent_hotel)).run()}
  if(b.action==="delete_property")await db.batch([db.prepare("UPDATE board_spaces SET property_id=NULL,type='custom' WHERE room_code=? AND property_id=?").bind(room,b.id),db.prepare("DELETE FROM properties WHERE room_code=? AND id=? AND owner_player_id IS NULL").bind(room,b.id)]);
  if(b.action==="save_space"){const x=b.space||{};await db.prepare("UPDATE board_spaces SET name=?,type=?,property_id=?,color=? WHERE id=? AND room_code=?").bind(String(x.name||"Petak").slice(0,40),String(x.type||"custom"),x.property_id||null,String(x.color||"#e7dfcf").slice(0,12),x.id,room).run()}
  if(b.action==="save_card"){const x=b.card||{},cid=String(x.id||id());if(!String(x.title||"").trim())return json({error:"Judul kartu wajib diisi"},400);await db.prepare("INSERT INTO cards(id,room_code,deck,title,description,amount,enabled) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET deck=excluded.deck,title=excluded.title,description=excluded.description,amount=excluded.amount,enabled=excluded.enabled").bind(cid,room,x.deck==="fund"?"fund":"chance",String(x.title).slice(0,50),String(x.description||"").slice(0,160),Math.trunc(Number(x.amount)||0),x.enabled===false?0:1).run()}
  if(b.action==="delete_card")await db.prepare("DELETE FROM cards WHERE room_code=? AND id=?").bind(room,b.id).run();return json({ok:true})
 }
 if(["build_property","sell_building","sell_property","pay_rent"].includes(b.action)){
  const p=await db.prepare("SELECT * FROM properties WHERE id=? AND room_code=?").bind(b.propertyId,room).first<any>();if(!p)return json({error:"Properti tidak ditemukan"},404);
  if(b.action==="pay_rent"){if(!p.owner_player_id||p.owner_player_id===me.id)return json({error:"Properti ini tidak memiliki pemilik lain"},400);const rent=await effectiveRent(db,room,p);if(rent<1||me.balance<rent)return json({error:"Saldo tidak cukup untuk membayar sewa"},400);await db.batch([db.prepare("UPDATE players SET balance=balance-? WHERE id=?").bind(rent,me.id),db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(rent,p.owner_player_id),db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,me.id,p.owner_player_id,rent,"rent",`Sewa ${p.name}`,"completed",Date.now())]);return json({ok:true})}
  if(p.owner_player_id!==me.id)return json({error:"Anda bukan pemilik properti ini"},403);const group=await groupProperties(db,room,p);
  if(b.action==="build_property"){if(!(await ownsCompleteGroup(db,room,p,me.id)))return json({error:"Kuasai seluruh properti dalam kompleks ini dahulu"},400);if(p.houses>=5)return json({error:"Properti sudah memiliki hotel"},400);const min=Math.min(...group.map((x:any)=>x.houses));if(p.houses>min)return json({error:"Bangunan wajib dibangun merata dalam satu kompleks"},400);const cost=p.houses===4?p.hotel_price:p.house_price;if(cost<1||me.balance<cost)return json({error:"Saldo tidak cukup untuk membangun"},400);await db.batch([db.prepare("UPDATE players SET balance=balance-? WHERE id=?").bind(cost,me.id),db.prepare("UPDATE properties SET houses=houses+1 WHERE id=? AND houses=?").bind(p.id,p.houses),db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,me.id,null,cost,p.houses===4?"build_hotel":"build_house",`${p.houses===4?"Bangun hotel":"Bangun rumah"} di ${p.name}`,"completed",Date.now())]);return json({ok:true})}
  if(b.action==="sell_building"){if(p.houses<1)return json({error:"Tidak ada bangunan untuk dijual"},400);const max=Math.max(...group.map((x:any)=>x.houses));if(p.houses<max)return json({error:"Bangunan wajib dijual merata dalam satu kompleks"},400);const value=Math.floor((p.houses===5?p.hotel_price:p.house_price)/2);await db.batch([db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(value,me.id),db.prepare("UPDATE properties SET houses=houses-1 WHERE id=? AND houses=?").bind(p.id,p.houses),db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,null,me.id,value,"sell_building",`Jual ${p.houses===5?"hotel":"rumah"} ${p.name} ke bank`,"completed",Date.now())]);return json({ok:true})}
  if(group.some((x:any)=>x.houses>0))return json({error:"Jual seluruh bangunan dalam kompleks ini dahulu"},400);const value=p.sell_price||Math.floor(p.price/2);await db.batch([db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(value,me.id),db.prepare("UPDATE properties SET owner_player_id=NULL WHERE id=?").bind(p.id),db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,null,me.id,value,"sell_property",`Jual ${p.name} ke bank`,"completed",Date.now())]);return json({ok:true})
 }
 if(b.action==="pay"){const amt=Math.floor(Number(b.amount));if(!amt||amt<1||amt>me.balance)return json({error:"Nominal tidak valid atau saldo kurang"},400);const to=b.target==="bank"?null:String(b.target);if(to&&!await valid(db,room,to))return json({error:"Pemain tujuan tidak ditemukan"},404);const q=[db.prepare("UPDATE players SET balance=balance-? WHERE id=?").bind(amt,me.id)];if(to)q.push(db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(amt,to));q.push(db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,me.id,to,amt,"payment",String(b.note||"Pembayaran").slice(0,50),"completed",Date.now()));await db.batch(q);return json({ok:true})}
 if(b.action==="go"||b.action==="draw_card"||b.action==="buy_property"){const settings=await db.prepare("SELECT * FROM room_settings WHERE room_code=?").bind(room).first<any>();let amt=settings?.go_salary??200,note="Melewati GO",type="bank_credit",to=me.id,from=null,status=settings?.require_bank_approval===0?"completed":"pending";if(b.action==="buy_property"){const p=await db.prepare("SELECT * FROM properties WHERE id=? AND room_code=?").bind(b.propertyId,room).first<any>();if(!p||p.owner_player_id)return json({error:"Properti sudah dimiliki"},409);if(me.balance<p.price)return json({error:"Saldo tidak cukup"},400);amt=p.price;note=`Beli ${p.name}`;type=`property:${p.id}`;from=me.id;to=null}else if(b.action==="draw_card"){const result=await db.prepare("SELECT * FROM cards WHERE room_code=? AND deck=? AND enabled=1").bind(room,b.deck==="fund"?"fund":"chance").all<any>();if(!result.results.length)return json({error:"Belum ada kartu aktif di dek ini"},404);const c=result.results[Math.floor(Math.random()*result.results.length)];note=c.description||c.title;amt=Math.abs(c.amount);type=c.amount>=0?"bank_credit":"bank_debit";if(c.amount<0){from=me.id;to=null}else{from=null;to=me.id}}await db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,from,to,amt,type,note,status,Date.now()).run();if(status==="completed"){if(from)await db.prepare("UPDATE players SET balance=balance-? WHERE id=?").bind(amt,from).run();if(to)await db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(amt,to).run();if(type.startsWith("property:"))await db.prepare("UPDATE properties SET owner_player_id=? WHERE id=? AND owner_player_id IS NULL").bind(from,type.split(":")[1]).run()}return json({ok:true})}
 if(b.action==="bank_transfer"){if(!me.is_host)return json({error:"Hanya bankir yang dapat mengirim dana bank"},403);const amt=Math.floor(Number(b.amount)),to=String(b.target);if(!amt||amt<1||!await valid(db,room,to))return json({error:"Data transaksi tidak valid"},400);await db.batch([db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(amt,to),db.prepare("INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),room,null,to,amt,"bank_credit",String(b.note||"Dana bank").slice(0,50),"completed",Date.now())]);return json({ok:true})}
 if(b.action==="approve"){if(!me.is_host)return json({error:"Hanya bankir yang dapat menyetujui"},403);const t=await db.prepare("SELECT * FROM transactions WHERE id=? AND room_code=? AND status='pending'").bind(b.transactionId,room).first<any>();if(!t)return json({error:"Transaksi sudah diproses"},409);if(!b.approve){await db.prepare("UPDATE transactions SET status='rejected' WHERE id=?").bind(t.id).run();return json({ok:true})}if(t.from_player_id){const payer=await valid(db,room,t.from_player_id);if(!payer||payer.balance<t.amount)return json({error:"Saldo pemain tidak lagi mencukupi"},409)}const propertyId=String(t.type).startsWith("property:")?String(t.type).split(":")[1]:null;if(propertyId){const property=await db.prepare("SELECT owner_player_id FROM properties WHERE id=? AND room_code=?").bind(propertyId,room).first<any>();if(!property||property.owner_player_id)return json({error:"Properti sudah dimiliki pemain lain"},409)}const qs=[];if(t.from_player_id)qs.push(db.prepare("UPDATE players SET balance=balance-? WHERE id=? AND balance>=?").bind(t.amount,t.from_player_id,t.amount));if(t.to_player_id)qs.push(db.prepare("UPDATE players SET balance=balance+? WHERE id=?").bind(t.amount,t.to_player_id));if(propertyId)qs.push(db.prepare("UPDATE properties SET owner_player_id=? WHERE id=? AND owner_player_id IS NULL").bind(t.from_player_id,propertyId));qs.push(db.prepare("UPDATE transactions SET status='completed' WHERE id=?").bind(t.id));await db.batch(qs);return json({ok:true})}
 return json({error:"Aksi tidak dikenali"},400)
 }catch(e){console.error(e);return json({error:"Permainan sedang tidak dapat diproses"},500)}}
